IF
	Die()
THEN
	RESPONSE #100
		Shout(ALERT)
END

IF
	BreakingPoint()
THEN
	RESPONSE #100
		DisplayStringHead(Myself,49766)  // I can't take this!
		Shout(ASSIST)
	RESPONSE #100
		DisplayStringHead(Myself,49767)  // No more!
		Shout(ASSIST)
	RESPONSE #100
		DisplayStringHead(Myself,49768)  // Mercy!
		Shout(ASSIST)
END

IF
	AttackedBy([GOODCUTOFF],DEFAULT)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Shout(ALERT)
		Enemy()
END

IF
	HitBy([GOODCUTOFF],CRUSHING)
THEN
	RESPONSE #100
		Shout(ALERT)
		Continue()
END

IF
	See([GOODCUTOFF])
	Allegiance(Myself,ENEMY)
	Global("ShoutedAlert","LOCALS",0)
THEN
	RESPONSE #100
		SetGlobal("ShoutedAlert","LOCALS",1)
		Shout(ALERT)
		Continue()
END

IF
	Heard([ANYONE],ALERT)
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		Enemy()
		Continue()
END

IF
	See(NearestEnemyOf(Myself))
	See([EVILCUTOFF])
	InMyGroup(LastSeenBy(Myself))
	HPPercentLT(Myself,25)
	HPGT(Myself,1)
	!Range(LastSeenBy(Myself),8)
	!GlobalTimerNotExpired("Whined","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Whined","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46151)  // Help!
		Shout(ASSIST)
	RESPONSE #100
		SetGlobalTimer("Whined","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,49763)  // I require assistance.
		Shout(ASSIST)
	RESPONSE #100
		SetGlobalTimer("Whined","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,49764)  // Defend me!
		Shout(ASSIST)
	RESPONSE #100
		SetGlobalTimer("Whined","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,49765)  // Slay my attacker!
		Shout(ASSIST)
END

IF
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN55",Myself)  // Potion of Superior Healing
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN55",Myself)  // Potion of Superior Healing
END

IF
	HPPercentLT(Myself,50)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN52",Myself)  // Potion of Extra Healing
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN52",Myself)  // Potion of Extra Healing
END

IF
	See(NearestEnemyOf(Myself))
	OR(2)
		Range(NearestMyGroupOfType,20)
		See(NearestMyGroupOfType([0.0.0.CLERIC_ALL]))
	HPPercentLT(Myself,35)
	!GlobalTimerNotExpired("CalledForHealing","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("CalledForHealing","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,72808)  // I need healing!
		Shout(HEALME)
		Continue()
END

IF
	Heard(NearestMyGroupOfType,HEALME)
	!StateCheck(LastHeardBy(Myself),STATE_REALLY_DEAD)
	HPPercentGT(Myself,75)
	See(LastHeardBy(Myself))
	Range(LastHeardBy(Myself),10)
	!Range(NearestMyGroupOfType([0.0.0.CLERIC_ALL]),20)
	!NumItemsGT("POTN55",LastHeardBy(Myself),0)  // Potion of Superior Healing
	NumItemsGT("POTN55",Myself,1)  // Potion of Superior Healing
	!GlobalTimerNotExpired("GaveAwayPotion","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("GaveAwayPotion","LOCALS",TWO_ROUNDS)
		DisplayStringHead(Myself,72809)  // Here! Catch!
		GiveItem("POTN55",LastHeardBy(Myself))  // Potion of Superior Healing
		SmallWait(2)
		ActionOverride(LastHeardBy(Myself),DisplayStringHead(Myself,73896))  // Got it!
		Continue()
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_HASTED)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN14",Myself)  // Oil of Speed
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN14",Myself)  // Oil of Speed
END

IF
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	HasItem("POTN10",Myself)  // Potion of Invisibility
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("POTN10",Myself)  // Potion of Invisibility
END

IF
	!Allegiance(Myself,NEUTRAL)
	Kit(Myself,SHADOWDANCER)
	Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_BLIND)
	!GlobalTimerNotExpired("OH_HIDE","LOCALS")
	CheckStatGT(Myself,20,HIDEINSHADOWS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_HIDE","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,101647)  // *attempts to hide in shadows*
		Hide()
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,EVILCUTOFF)
	!Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_BLIND)
	!GlobalTimerNotExpired("OH_HIDE","LOCALS")
	CheckStatGT(Myself,20,HIDEINSHADOWS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_HIDE","LOCALS",ONE_ROUND)
		Hide()
		SetInterrupt(TRUE)
END

IF
	Allegiance(Myself,GOODCUTOFF)
	!Detect(NearestEnemyOf(Myself))
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_BLIND)
	!GlobalTimerNotExpired("OH_HIDE","LOCALS")
	CheckStatGT(Myself,20,HIDEINSHADOWS)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("OH_HIDE","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,101647)  // *attempts to hide in shadows*
		Hide()
		SetInterrupt(TRUE)
END

IF
	!GlobalTimerNotExpired("OHR_DI","LOCALS")
	CheckStatGT(Myself,20,DETECTILLUSIONS)
	!ModalState(DETECTTRAPS)
	OR(5)
		See(NearestEnemyOfType([0.0.0.0.0.ILLUSIONARY]))
		StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
		StateCheck(NearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
		StateCheck(SecondNearestEnemyOf(Myself),STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		SetGlobalTimer("OHR_DI","LOCALS",ONE_ROUND)
		DisplayString(Myself,101646)  // *attempts to detect illusions*
		FindTraps()
END

IF
	HasItem("POTN34",Myself)  // Potion of Magic Protection
	CheckStatLT(Myself,100,RESISTMAGIC)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		UseItem("POTN34",Myself)  // Potion of Magic Protection
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
	HasItem("POTN21",Myself)  // Potion of Clarity
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		UseItem("POTN21",Myself)  // Potion of Clarity
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
	HasItem("POTN45",Myself)  // Potion of Freedom
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		UseItem("POTN45",Myself)  // Potion of Freedom
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
END

IF
	HaveSpell(ASSASSIN_POISON)  // SPCL423.SPL (Poison Weapon)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTPOISON)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("OH_Poison","LOCALS")
	!StateCheck(Myself,STATE_SILENCED)
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_Poison","LOCALS",FIVE_ROUNDS)
		Spell(Myself,ASSASSIN_POISON)  // SPCL423.SPL (Poison Weapon)
		SetInterrupt(TRUE)
END

IF
	HaveSpell(ASSASSIN_POISON)  // SPCL423.SPL (Poison Weapon)
	StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_SILENCED)
	CheckStatLT(NearestEnemyOf(Myself),100,RESISTPOISON)
	!GlobalTimerNotExpired("OH_Poison","LOCALS")
	Range(NearestEnemyOf(Myself),30)
THEN
	RESPONSE #100
		NoAction()
END

IF
	HaveSpellRES("SPSD02")  // Shadowstep
	!HasItem("POTN10",Myself)  // Potion of Invisibility
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_SILENCED)
	Range(NearestEnemyOf(Myself),30)
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	!GlobalTimerNotExpired("OH_SSTEP","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("OH_SSTEP","LOCALS",7)
		SpellRES("SPSD02",Myself)  // Shadowstep
		RunAwayFromNoInterruptNoLeaveArea(NearestEnemyOf(Myself),30)
END

IF
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Allegiance(Myself,ENEMY)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!GlobalTimerNotExpired("RingTimer","LOCALS")
	HasItem("RING05",Myself)  // Sandthief's Ring
THEN
	RESPONSE #100
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SetGlobalTimer("RingTimer","LOCALS",ONE_ROUND)
		DisplayStringHead(Myself,46150)  // *quaffs a potion*
		UseItem("RING05",Myself)  // Sandthief's Ring
END

IF
	HaveSpellRES("SPCL913")  // Evasion
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("Evasion","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Evasion","LOCALS",THREE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SpellRES("SPCL913",Myself)  // Evasion
END

IF
	HaveSpellRES("SPCL917")  // Avoid Death
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Allegiance(Myself,ENEMY)
	See(NearestEnemyOf(Myself))
	!GlobalTimerNotExpired("AvoidDeath","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("AvoidDeath","LOCALS",FIVE_ROUNDS)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SpellRES("SPCL917",Myself)  // Avoid Death
END

IF
	!Allegiance(Myself,ENEMY)
THEN
	RESPONSE #100
		NoAction()
END

IF
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	OR(3)
		See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
		See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
		See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
THEN
	RESPONSE #100
		Continue()
END

IF
	OR(3)
		See(NearestEnemyOfType([GOODCUTOFF.0.0.BARD]))
		See(NearestEnemyOfType([GOODCUTOFF.0.0.DRUID_ALL]))
		See(NearestEnemyOfType([GOODCUTOFF.0.0.CLERIC_ALL]))
THEN
	RESPONSE #100
		Continue()
END

IF
	OR(2)
		See(ThirdNearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
		See(ThirdNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
THEN
	RESPONSE #100
		Continue()
END

IF
	OR(2)
		See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
		See(SecondNearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
THEN
	RESPONSE #100
		Continue()
END

IF
	OR(2)
		See(NearestEnemyOfType([GOODCUTOFF.0.0.SORCERER]))
		See(NearestEnemyOfType([GOODCUTOFF.0.0.MAGE_ALL]))
THEN
	RESPONSE #100
		Continue()
END

IF
	Heard(NearestMyGroupOfType(Myself),ASSIST)
	!StateCheck(LastHeardBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_INVISIBLE)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CHARMED)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_HELPLESS)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_SLEEPING)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_STUNNED)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CONFUSED)
	See(LastAttackerOf(LastHeardBy(Myself)))
THEN
	RESPONSE #100
		Continue()
END

IF
	Heard(NearestMyGroupOfType,ASSIST)
	See(LastHeardBy(Myself))
	!See(LastAttackerOf(LastHeardBy(Myself)))
	!StateCheck(LastHeardBy(Myself),STATE_REALLY_DEAD)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_INVISIBLE)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_IMPROVEDINVISIBILITY)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CHARMED)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_HELPLESS)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_SLEEPING)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_STUNNED)
	!StateCheck(LastAttackerOf(LastHeardBy(Myself)),STATE_CONFUSED)
	!HPPercentLT(Myself,50)
	!Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		MoveToObject(LastHeardBy(Myself))
END

IF
	AttackedBy([ANYONE],DEFAULT)
	See(LastAttackerOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	Range(NearestEnemyOf(Myself),4)
	See(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		Continue()
END

IF
	!Allegiance(LastSeenBy(Myself),GOODCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		MoveToObject([GOODCUTOFF])
END

IF
	!Allegiance(LastSeenBy(Myself),GOODCUTOFF)
	!See([GOODCUTOFF])
	Global("bd_search_timer","locals",0)
	Global("bd_default_loc","locals",0)
	!StateCheck(LastSeenBy(Myself),STATE_REALLY_DEAD)
	Range(LastSeenBy(Myself),42)
THEN
	RESPONSE #100
		SaveObjectLocation("LOCALS","bd_default_loc",LastSeenBy(Myself))
		MoveToSavedLocation("bd_default_loc","LOCALS")
END

IF
	!See([GOODCUTOFF])
	Global("bd_search_timer","locals",0)
	Global("bd_default_loc","locals",0)
THEN
	RESPONSE #100
		SetGlobalTimerRandom("bd_search_timer","locals",THREE_MINUTES,FIVE_ROUNDS)
		SetGlobalTimerRandom("bd_search2_timer","locals",FIVE_ROUNDS,NINE_MINUTES)
	RESPONSE #200
		SetGlobal("bd_search_timer","locals",1)
		SetGlobalTimerRandom("bd_search2_timer","locals",THREE_MINUTES,FIVE_ROUNDS)
END

IF
	!See([GOODCUTOFF])
	Global("bd_search_timer","locals",0)
	!Global("bd_default_loc","locals",0)
	NearSavedLocation(Myself,"LOCALSbd_default_loc",7)
THEN
	RESPONSE #100
		SetGlobalTimerRandom("bd_search_timer","locals",THREE_MINUTES,FIVE_ROUNDS)
END

IF
	!See([GOODCUTOFF])
	!Global("bd_search_timer","locals",0)
	GlobalTimerNotExpired("bd_search_timer","locals")
THEN
	RESPONSE #100
		RandomWalkContinuous()
END

IF
	!See([GOODCUTOFF])
	!Global("bd_search_timer","locals",0)
	GlobalTimerExpired("bd_search_timer","locals")
	!GlobalTimerNotExpired("bd_search2_timer","locals")
THEN
	RESPONSE #100
		SetGlobalTimerRandom("bd_search_timer","locals",THREE_MINUTES,FIVE_ROUNDS)
		SetGlobalTimerRandom("bd_search2_timer","locals",FIVE_ROUNDS,NINE_MINUTES)
	RESPONSE #200
		SetGlobalTimerRandom("bd_search2_timer","locals",THREE_MINUTES,FIVE_ROUNDS)
END

IF
	See(LastSeenBy(Myself))
	Allegiance(LastSeenBy(Myself),GOODCUTOFF)
	OR(2)
		!Global("bd_search_timer","locals",0)
		!Global("bd_default_loc","locals",0)
THEN
	RESPONSE #100
		SetGlobal("bd_search_timer","locals",0)
		SetGlobal("bd_default_loc","locals",0)
		Continue()
END

IF
	!See([GOODCUTOFF])
	!Global("bd_search_timer","locals",0)
THEN
	RESPONSE #100
		NoAction()
END

IF
	HaveSpellRES("SPCL916")  // Assassination
	!GlobalTimerNotExpired("DrankPotionTimer","LOCALS")
	Range(LastSeenBy(Myself),10)
	OR(2)
		StateCheck(Myself,STATE_INVISIBLE)
		StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!GlobalTimerNotExpired("Assassinate","LOCALS")
THEN
	RESPONSE #100
		SetGlobalTimer("Assassinate","LOCALS",ONE_ROUND)
		SetGlobalTimer("DrankPotionTimer","LOCALS",ONE_ROUND)
		SpellRES("SPCL916",Myself)  // Assassination
END

IF
	OR(2)
		StateCheck(Myself,STATE_INVISIBLE)
		StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		MoveToObject(LastSeenBy(Myself))
		AttackReevaluate(LastSeenBy(Myself),15)
		RunAwayFrom(LastSeenBy(Myself),30)
END

IF
	Range(LastSeenBy(Myself),10)
	HPPercentLT(Myself,20)
	OR(2)
		HasItem("POTN55",Myself)  // Potion of Superior Healing
		Range(NearestMyGroupOfType,25)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		RunAwayFrom(LastSeenBy(Myself),45)
		SetInterrupt(TRUE)
END

IF
	Range(LastSeenBy(Myself),10)
	HPPercentLT(Myself,20)
	!HasItem("POTN55",Myself)  // Potion of Superior Healing
	False()
	!Range([ANYONE],15)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,49767)  // No more!
		EscapeArea()
END

IF
	!Range(LastSeenBy(Myself),6)
	OR(2)
		StateCheck(Myself,STATE_INVISIBLE)
		StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		MoveToObject(LastSeenBy(Myself))
END

IF
	Range(LastSeenBy(Myself),6)
	OR(2)
		StateCheck(Myself,STATE_INVISIBLE)
		StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),30)
END

IF
	Range(LastSeenBy(Myself),10)
	HPPercentLT(Myself,20)
	OR(2)
		HasItem("POTN55",Myself)  // Potion of Superior Healing
		Range(NearestMyGroupOfType,25)
THEN
	RESPONSE #100
		RunAwayFrom(LastSeenBy(Myself),45)
END

IF
	Range(NearestEnemyOf(Myself),10)
	HPPercentLT(Myself,20)
	!HasItem("POTN55",Myself)  // Potion of Superior Healing
	OR(2)
		!See([ANYONE])
		!Range([ANYONE],15)
THEN
	RESPONSE #100
		DisplayStringHead(Myself,49767)  // No more!
		EscapeArea()
END

IF
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		RunAwayFrom(NearestEnemyOf(Myself),60)
	RESPONSE #50
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END

IF
	RandomNum(2,1)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!Range(NearestEnemyOf(Myself),15)
THEN
	RESPONSE #100
		EquipRanged()
		AttackReevaluate(NearestEnemyOf(Myself),45)
END

IF
	RandomNum(2,1)
	!StateCheck(Myself,STATE_INVISIBLE)
	!StateCheck(Myself,STATE_IMPROVEDINVISIBILITY)
	!Range(NearestEnemyOf(Myself),5)
THEN
	RESPONSE #100
		RunAwayFrom(NearestEnemyOf(Myself),30)
END

IF
        True()
THEN
	RESPONSE #100
		EquipMostDamagingMelee()
		AttackReevaluate(LastSeenBy(Myself),45)
END



